urltemplates/learning_templates/basic_app/urls.py
from django.urls import path
from basic_app import views

# Template Tagging

app_name = "basic_app"

urlpatterns = [
    path('relative', views.relative, name='relative'),
    path('other', views.other, name='other'),
]

urltemplates/learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path , include
from basic_app import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('basic_app/',include('basic_app.urls')),

]

urltemplates/learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

urltemplates/learning_templates/basic_app/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'index.html')



def other(request):
    return render(request, 'other.html')


def relative(request):
    return render(request, 'relative_url_template.html')

urltemplates/learning_templates/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}">BRAND</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'admin:index' %}">Admin</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'basic_app:other' %}">Other</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'basic_app:relative' %}">Relative</a>
        </li>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
    {% block body_block %}
        <!-- Anything outside this block will be extended -->


    {% endblock %}
</div>
</body>
</html>

urltemplates/learning_templates/templates/index.html
<!DOCTYPE html>
{% extends 'base.html' %}
 {% block body_block %}
<h1>This is the Main  page</h1>
<h2> This is the example to template inheritance</h2>
 {% endblock %}

urltemplates/learning_templates/templates/other.html
<!DOCTYPE html>
{% extends 'base.html' %}
 {% block body_block %}
<h1>This is the other page</h1>
<h2> This is the example to template inheritance</h2>
 {% endblock %}

urltemplates/learning_templates/templates/relative_url_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>This is the Relative Page</h1>
<a href="{% url 'basic_app:other' %}">Link to Other Page</a><br>
<a href="{% url 'admin:index' %}">Link to Admin Page</a> <br>
<a href="{% url 'index' %}">Link to Index page</a>
</body>
</html>